[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/kit"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[override]]
  name = "gopkg.in/alecthomas/kingpin.v3-unstable"
  revision = "63abe20a23e29e80bbef8089bd3dee3ac25e5306"

[[constraint]]
  branch = "master"
  name = "github.com/go-chi/chi"

[[override]]
  branch = "master"
  name = "github.com/smallstep/cli"

[[override]]
  branch = "master"
  name = "github.com/smallstep/nosql"

[[override]]
  branch = "master"
  name = "github.com/smallstep/certificates"

[[override]]
  name = "github.com/urfave/cli"
  revision = "b67dcf995b6a7b7f14fad5fcb7cc5441b05e814b"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.24.0"  

[prune]
  go-tests = true
  unused-packages = true
