[[constraint]]
  branch = "master"
  name = "github.com/go-ocf/kit"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.22.0"

[prune]
  go-tests = true
  unused-packages = true
